#
# _____                           ____              _
#|  _ \| | __ _ _   _  ___ _ __ / ___|_ __ __ _ ___| |__   ___ _ __
#| |_) | |/ _` | | | |/ _ \ '__| |   | '__/ _` / __| '_ \ / _ \ '__|
#|  __/| | (_| | |_| |  __/ |  | |___| | | (_| \__ \ | | |  __/ |
#|_|   |_|\__,_|\__, |\___|_|   \____|_|  \__,_|___/_| |_|\___|_|
#               |___/


# true hides the plugin from /plugins and /pl for everyone that doesn't have the crasher.use permission.
# false will disable the event that will hide the plugin.
plugin-hider: true

# true disables the entity method. This method is rather heavy and should only be used if the other methods aren't working.
# false will keep the entity method enabled.
disable-entity-method: false
