#    _____  _                        _____               _
#   |  __ \| |                      / ____|             | |
#   | |__) | | __ _ _   _  ___ _ __| |     _ __ __ _ ___| |__   ___ _ __
#   |  ___/| |/ _` | | | |/ _ \ '__| |    | '__/ _` / __| '_ \ / _ \ '__|
#   | |    | | (_| | |_| |  __/ |  | |____| | | (_| \__ \ | | |  __/ |
#   |_|    |_|\__,_|\__, |\___|_|   \_____|_|  \__,_|___/_| |_|\___|_|
#                    __/ |
#                   |___/

# This option determines whether the plugin will check for an update on startup.
update-checker:
  enabled: true

  # When an update is found, should it be printed to the console?
  print-to-console: true

  # When an update is found, should players with the permission "PlayerCrasher.UpdateNotify" be notified?
  notify-in-game: true