name: PlayerCrasher
author: Bram
description: Crashes players' clients by sending them funny packets.
website: https://github.com/Bram1903/MinecraftPlayerCrasher
main: com.deathmotion.playercrasher.PlayerCrasher
version: '2.0.0'
api-version: '1.13'
folia-supported: true
load: POSTWORLD
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
permissions:
  PlayerCrasher.Crash:
    description: Allows the player to use the /crash command.
    default: true
  PlayerCrasher.Bypass:
    description: Allows the player to bypass a crash.
    default: op
  PlayerCrasher.Alerts:
    description: Allows the player to receive a notification when a player crashes.
    default: op
  PlayerCrasher.UpdateNotify:
    description: Allows the player to receive a notification when an update is found.
    default: op
