name: PlayerCrasher
author: Bram
description: Crashes players' clients by sending them funny packets.
website: https://github.com/Bram1903/MinecraftPlayerCrasher
main: com.deathmotion.playercrasher.PCBukkit
version: '${version}'
api-version: '1.13'
folia-supported: true
load: POSTWORLD
depend:
  - packetevents
commands:
  PlayerCrasher:
    description: Base command for PlayerCrasher.
    aliases:
      - pc
  Crash:
    description: Crashes a player's client.
    permission: PlayerCrasher.Crash
    permission-message: Unknown command. Type "/help" for help
    aliases:
      - crashplayer
      - bomb
  CrashInfo:
    description: Checks the brand and version of a player's client.
    permission: PlayerCrasher.CrashInfo
    permission-message: Unknown command. Type "/help" for help
    aliases:
      - brand
permissions:
  PlayerCrasher.Crash:
    description: Allows the player to use the /crash command.
    default: op
  PlayerCrasher.Bypass:
    description: Allows the player to bypass a crash.
    default: op
  PlayerCrasher.Alerts:
    description: Allows the player to receive a notification when a player crashes.
    default: op
  PlayerCrasher.CrashInfo:
    description: Allows the player to use the /crashinfo command.
    default: op
  PlayerCrasher.UpdateNotify:
    description: Allows the player to receive a notification when an update is found.
    default: op